### ISSUE TITLE
Login - default to HTTPS if user enters URL without a scheme

### ISSUE THREAD

**Issue by issmirnov** [vickychijwani/quill#132]
- App version: 1.1.0
- Android version: 6.0.1
- Device name: Moto X 2014 (XT1095)

----

When there is no protocol specified in the blog URL, the app defaults to HTTP and throws an error if the blog is HTTPS exclusive. 

The new user flow would be improved if the app tried both HTTP and HTTPS. If both endpoints return valid results, perhaps a popup asking the user which to use would make sense. Or, I would argue it would be better to default to HTTPS to promote security.

Steps to reproduce:
- install app
- install blog on HTTPS, with a 301 redirect from 80 -> 443 (my blog.ivansmrinov.name does this)
- type in the url with no schema: `blog.ivansmirnov.name`
- observe error that **http://**blog.ivansmirnov.name is unreachable.

Overall the app looks fantastic already, this is a minor polish that would improve user delight!

**Comment by vickychijwani** [comment]
Thanks for the feedback! It definitely helps me prioritize what to work on next :)

I agree, this is important to get right. I actually had this in mind myself, even made a note in the code [here](https://github.com/vickychijwani/quill/commit/1804408a5dcd0080a512b1f151ca5b3a512afdbd).
