### ISSUE TITLE
Tags and Featured Post

### ISSUE THREAD

**Issue by Dennis-Mayk** [vickychijwani/quill#141]
- App version: 1.2.2
- Android version: 4.4.4
- Device name: Samsung Galaxy Note 2

----

1.) Tags cant have a space in between in app. Like in "Getting Started".

2.) Featured post option seems to be not available in app.

**Comment by vickychijwani** [comment]
Hi Dennis, this is great feedback - thanks! I've fixed the first issue (tags can't have spaces) in commit 243e5a5. The new behaviour is to separate tags with commas instead.

I'll get to the second one (featured post) in some time.

**Comment by Dennis-Mayk** [comment]
Great thanks for fixing.
