### ISSUE TITLE
User with only "Author" role are not handled correctly

### ISSUE THREAD

**Issue by yffengdong** [vickychijwani/quill#145]
FILL THESE DETAILS FIRST:

- App version: <1.3.3>
- Android version: <4.1.1>
- Device name: la-q1

----

DESCRIBE YOUR ISSUE HERE

I know, the ghost blog's background account has four. About: owner, administration, editor, author.
And the bug is no full privileges. About I'm author account, I can't edit others account post. So, quill can't pull, and always loading. The worst is forced to stop.

**Comment by vickychijwani** [comment]
Hi @yffengdong. I didn't really test how Quill works with different roles like owner, author, editor, etc. I will look into this bug.

Till then, can you try logging out of Quill and then logging back in? That will remove your edits on the other post and you should be able sync again.

**Comment by yffengdong** [comment]
Yeah, but I can edit my post about author. Edit others post will appear this bug.

**Comment by vickychijwani** [comment]
Right, understood. I'll try to reproduce this bug on my machine.

**Comment by yffengdong** [comment]
Thanks

**Comment by vickychijwani** [comment]
@yffengdong I was able to reproduce and fix the issue. Will upload a new version to the Play Store shortly. Thanks for reporting the bug!
