### ISSUE TITLE
Overhaul image upload

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#155]
The current image upload code suffers from several potential issues because of the [unnecessary, forced conversion to JPEG](https://github.com/vickychijwani/quill/blob/da3974b93724c942cb34dc5d7829c0e1799a2c85/app/src/main/java/me/vickychijwani/spectre/view/fragments/PostEditFragment.java#L350-L355), although no user has come forward with these yet:

- The image may be of lower quality than the original due to JPEG compression
- The user may (reasonably) not expect their image to be messed with on the way up
- The file may get blown up in size depending on the source encoding and so on
- Some images may not be converted correctly, for any reason - if Ghost can work with it, we shouldn't get in the way
- It slows down the image upload process by performing this extra conversion

Given that the JPEG compression is 100% unnecessary and was only done for early ease-of-implementation, it should be removed now. The app should directly upload whatever file was chosen to Ghost. [This blog post](https://futurestud.io/tutorials/retrofit-2-how-to-upload-files-to-server#androidclientcode) dives deep into how to do exactly that, and the code seems robust enough to handle different Android versions and so on.

----

Related: #154, #153

**Comment by vickychijwani** [comment]
I've ended up using a hybrid approach that first tries to get the image path and upload it directly, and failing that falls back to the old JPEG conversion approach. This should be more robust than both methods while preserving data integrity as far as possible. See the commit message for more details.

**Comment by vickychijwani** [comment]
This deserves re-visting after further [helpful advice from StackOverflow](http://stackoverflow.com/a/39490576/504611). It should be possible to simply get an `InputStream` from the picked `Uri` and write it to a `File` without decoding it into a `Bitmap` first, that way we preserve the original encoding exactly and don't have mess around with Uri => path conversion in a hacky way.

**NOTE:** Retrofit 1.x supported [uploading directly from an `InputStream`](http://stackoverflow.com/a/22574877/504611), will have to find the equivalent for Retrofit 2.x or ask about it on their Github repo.

**Comment by RcrdBrt** [comment]
Images inserted into articles from the Quill app end up displaying the *broken image icon* (see below) after **some time** (undefined amount of time ranging from 2 days to 2 weeks on avg) for no apparent reason. 

Images uploaded from the ghost web admin interface from a desktop PC do not suffer this.

![google_broken_image_00_b_logo_detail](https://cloud.githubusercontent.com/assets/1354394/23104987/42b60e50-f6d8-11e6-9d54-a3a8a64c0b9a.gif)

Is this issue related to the problem I described above?

**Comment by vickychijwani** [comment]
@RcrdBrt if the URL for the image is still correct after the broken image shows up, and if the same image is still correctly displayed on the Ghost web interface, then the likely culprit is your internet connection. Could you try going to App Settings, clear the cache, and open the post again with a stable connection? At least that would confirm the problem.

**Comment by RcrdBrt** [comment]
The url is fine when the image breaks, it was the first thing that came to my mind to troubleshoot this. Those images are displayed correctly for like 2 weeks and then suddenly the Ghost blog fails to "render" them both on mobile and desktop. I downloaded the actual files uploaded from the app via `rsync` and I can open and watch them just fine (also their thumbnails if it can help) from a random image viewer or even Google Chrome.

**Comment by vickychijwani** [comment]
I see. Can you try the cache clearing workaround I described above?

**Comment by RcrdBrt** [comment]
Sure, I'll let you know if it still happens.

Thanks!

**Comment by vickychijwani** [comment]
Oh you know what, I just read your previous comment carefully and noticed you said it fails to render even on **desktop**. That's... interesting, and strange.

I think the new update (v1.5.5) _might_ fix the issue, because before this I used to convert (i.e., decode and re-encode) the image to a JPEG, but now I upload the image exactly in its original format. Let me know if you still see it after updating and uploading some new images.

**Comment by RcrdBrt** [comment]
Yeah, it fails on desktop too. I thought that maybe there was some shared cache system I wasn't aware of and I was trying to do your suggestion anyway.
I read about the JPEG not-necessary compression your app does. I hope that is the issue, but I don't know since whatsapp shared images are already jpeg and even those ones get broken after some time if I upload them with Quill.

**Comment by vickychijwani** [comment]
> but I don't know since whatsapp shared images are already jpeg and even those ones get broken after some time

In older app versions, even if an image was _already_ a JPEG, it would _still_ have been re-encoded - so the new version might fix it.
