### ISSUE TITLE
Unable to login if Ghost admin is at /blog/ghost

### ISSUE THREAD

**Issue by RcrdBrt** [vickychijwani/quill#161]
- Ghost version: 0.11.4
- App version: 1.5.3

----

I can't login into my blog anymore since the latest updates. My ghost installation is under example.com/blog/ if it helps. I noticed that the app had troubles handling that, redirecting me to the root URL sometimes instead. So this detail might help. 
The app is just showing "unexpected error during sign in. Please try again" toast. 
I already tried clearing the cache or reinstalling, still no luck.

**Comment by vickychijwani** [comment]
Hi @RcrdBrt, your detail about the blog being under example.com/blog/ seems spot-on - I don't test with that kind of setup. I should probably add a unit test for this case.

I'll fix this. Thanks for reporting!

**Comment by vickychijwani** [comment]
Would you mind sharing your blog URL for testing purposes? The only thing I will do is try to login with incorrect username/password a few times, of course.

**Comment by RcrdBrt** [comment]
Sure. Https://rcrdbrt.com/blog

**Comment by vickychijwani** [comment]
This is fixed. There are also now [unit tests](https://circleci.com/gh/vickychijwani/quill/162) in place to check for various types of blogs (`blog.example.com`, `example.com/blog`, `https://my-blog.com`, etc), so hopefully this kind of issue won't happen again.
