### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [vickychijwani/quill#165]
Hi @vickychijwani 

Since the app is licensed under MIT License, can you consider adding this app to the F-Droid repository? (I don't know if you're using proprietary libraries, but it doesn't works with F-Droid, we sometimes can build the app without them)

I can give you documentation and links if you need it ;)

**Comment by vickychijwani** [comment]
Hey @Poussinou 👋 

Quill is not compatible with [F-Droid's inclusion policy](https://f-droid.org/wiki/page/Inclusion_Policy). It relies heavily on Crashlytics and Answers (both part of [Fabric](https://fabric.io/)) for crash-reporting and analytics respectively. Neither of these have a high-quality open-source equivalent, nor can I make do without them - having insight into what areas of the app to focus my limited time on is immensely valuable.

I'm sorry, but this is simply not possible at the moment.

**Comment by Poussinou** [comment]
Thanks for your answer :+1: 

Still a good thing to have your app as free software ;)

No problem
