### ISSUE TITLE
Add a "Turn this post into a page" checkbox in the post sidebar

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#166]
A post can be turned into a "page" in Ghost, which means that it's like a normal post except it doesn't appear in the post list / feed. This is useful (for instance) for an About page.

**Comment by metatribal** [comment]
Alternatively, a static icon could be added to indicate the post is static.  This looks as though it would require the least logic and wouldn't require any changes to the existing state messages.  Perhaps the "book" or"bookmark" icon from [Google Material Icons](https://material.io/icons/)

**Comment by vickychijwani** [comment]
@metatribal this feature is coming in the next version 🙂

For now I opted not to change the icon or text in the post list because of a few reasons (hard to find a good icon that conveys the idea without compromising usability, and changing text would double the number of status strings so it doesn't seem worth the clutter). This can be revisited in future.
