### ISSUE TITLE
Cannot login to my blog

### ISSUE THREAD

**Issue by renehernandez** [vickychijwani/quill#169]
FILL THESE DETAILS FIRST:

- Ghost version: 1.5.2
- App version: 1.5.6
----

DESCRIBE YOUR ISSUE HERE

**Comment by vickychijwani** [comment]
Hi @renehernandez 👋

The Ghost 1.x support in Quill is in beta right now. To get it, you'll need to opt in to the beta here: https://play.google.com/apps/testing/me.vickychijwani.spectre

Just follow the instructions there and you should be able to log in. To confirm you have the beta installed, check your system settings > Apps > Quill. The version should be 2.0.0-beta2.

Let me know if you run into any problems! Closing this as it's not really an issue.
