### ISSUE TITLE
Access denied to Ghost 1.6.2

### ISSUE THREAD

**Issue by pbout** [vickychijwani/quill#170]
FILL THESE DETAILS FIRST:

- Ghost version: 1.6.2
- App version: 1.5.6

----

I tried logging in to a newly installed Docker image of ghost. The image is hosted on a vps without a name. I access the ghost image from a browser using "http://123.123.123.123:4040"
I created a user and used the credentials but access was always denied. If I enter credentials with an error the application hanged.

**Comment by vickychijwani** [comment]
Hi @pbout 👋

The Ghost 1.x support in Quill is in beta. You can opt-in to the beta program here: https://play.google.com/apps/testing/me.vickychijwani.spectre

What you downloaded from the Play Store is the stable version of the app (v1.5.6), that currently works only with Ghost 0.11 or older. I'm in the process of rolling out the beta version for everyone over the next few days, or you can start using it now from the link above.

Let me know if you face any issues or need further help!
