### ISSUE TITLE
Persist access token until it expires

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#3]
I'm not sure if this is absolutely needed, but I'll make a note of it in any case.

**Comment by lifehome** [comment]
Checkbox -> Remember me?

**Comment by vickychijwani** [comment]
Actually this issue is not for remembering the password (which is already taken care of). If you see issue #1, you'll notice that I'm using a hack to get around the fact that Ghost doesn't have a public API yet. So when I get an access_token, it's only valid for 60 minutes, but I can always request a new access_token because I have the username and password. This issue is meant to remind me that I could instead persist the access_token in a database and request a new one only if the current one has expired.
