### ISSUE TITLE
Move to the new Android Design Support Library

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#73]
Now that several Material Design components are available in the official Android Design Support Library, we should start using those components rather than third-party libraries for maximum consistency with the material design spec and to reduce APK size (hopefully). Third-party libs currently being used, that need to be replaced:

- [x] FloatingActionButton (post list and post editor)
- [x] MaterialEditText (EditText with floating labels on login screen)
- ~~ObservableScrollView (for collapsing toolbar in post editor)~~

**Comment by vickychijwani** [comment]
There are quite a few bugs in the design library at this point, waiting for them to be resolved. (private link: https://code.google.com/p/android/issues/list?can=5&q=&colspec=ID+Type+Status+Owner+Summary+Stars&cells=tiles)

**Comment by prakhar1989** [comment]
Haha! Who's *we*? :grinning: The [CoordinatorLayout](http://developer.android.com/reference/android/support/design/widget/CoordinatorLayout.html?utm_campaign=io15&utm_source=dac&utm_medium=blog) looks really cool. Make some use of that? :dancers:

**Comment by vickychijwani** [comment]
"We" is to make potential contributors feel welcome, it creates a sense of community I think :). CoordinatorLayout is currently riddled with bugs, definitely planning to use it when they're resolved.

**Comment by prakhar1989** [comment]
:thumbs_up: :D

**Comment by vickychijwani** [comment]
The new 22.2.1 release of the support library fixes most of the major issues, now is a good time to try it out.

**Comment by prakhar1989** [comment]
:metal:

**Comment by vickychijwani** [comment]
CoordinatorLayout is proving to be not-so-easy to use, even though it can do so much out of the box. Moving on for now, will wrestle with it later.
