### ISSUE TITLE
Image uploads in post editor

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#9]
This issue belongs to the create / edit post epic: #5.

------

This option should behave differently based on whether image storage is enabled in Ghost.

- [x] Allow inserting an image by uploading it from SD card, gallery, Google Photos, Dropbox, etc
- [x] Allow inserting an image by URL
- [ ] Disallow image uploads if file storage on server is disabled

------

To upload an image:

```http
POST /ghost/api/v0.1/uploads
Authorization: Bearer <access_token>
Content-Type: multipart/form-data; boundary=---------------------------17198750393646391371265188423

-----------------------------17198750393646391371265188423
Content-Disposition: form-data; name="uploadimage"; filename="<filename>.jpg"
Content-Type: image/jpeg
<image_data>
-----------------------------17198750393646391371265188423--

200 OK
Content-Type: application/json; charset=utf-8

/content/images/2015/08/<filename>.jpg
```

To check whether file storage is enabled:

```http
GET /ghost/api/v0.1/configuration/fileStorage/
Authorization: Bearer <access_token>

200 OK
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Content-Type: application/json; charset=utf-8
ETag: W/"37-5d4948bf"

{
    "configuration": [
        {
            "key": "fileStorage", 
            "value": false
        }
    ]
}
```

**Comment by lifehome** [comment]
Question brings up, if config.js has disabled the file upload, Ghost will prompt for URL linking instead of accepting file uploads, ideas to solve this?

**Comment by vickychijwani** [comment]
Hmm, that's a good point. I'll investigate if there's a way to query Ghost and find out if uploads are disabled. In that case we can just prompt for URL linking just like the web client.

**Comment by vickychijwani** [comment]
Ghost's API has a way to figure out if file storage is disabled:

```http
GET /ghost/api/v0.1/configuration/fileStorage/
Authorization: Bearer <access_token>

200 OK
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Content-Type: application/json; charset=utf-8
ETag: W/"37-5d4948bf"

{
    "configuration": [
        {
            "key": "fileStorage", 
            "value": false
        }
    ]
}
```
